Moved `fs-extra` to dependencies
Having `fs-extra` as a dev dependency does not allow you to use this as a bluerprint when creating a new sails app. Here is what I had when I tried to create a new app:
```
$ npm install -g sails ember-cli sails-generate-new-ember sails-generate-frontend-ember sails-generate-backend-ember
#...
$ sails generate ember-app myApp
error: Error in "ember-app" generator (loaded from sails-generate-new-ember)

/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/index.js:51
      throw e;
            ^
Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/sails-generate-new-ember/lib/after.js:5:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I could generate it after going doing this:
```
$ cd /usr/local/lib/node_modules/sails-generate-new-ember
$ npm install fs-extra
```

So it is a required dep, and that is the reason of my PR